source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
# 忽略引入库的所有警告
#inhibit_all_warnings!
use_frameworks!

def pods
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireNetworkActivityIndicator', '2.2'
    pod 'SwiftyJSON'
end

target 'ShecareSDKDemo' do
    pods
end
